# Generated by Django 5.1.1 on 2024-11-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarterly_projection_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarterlydata',
            name='expenses',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quarterlydata',
            name='quarter',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='quarterlydata',
            name='sales',
            field=models.FloatField(),
        ),
    ]
